CREATE SCHEMA `sign-up-in` IF NOT EXISTS DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;

CREATE TABLE IF NOT EXISTS`sign-up-in`.`USERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`)
  );